### ISSUE TITLE
vagrant box `boxcutter/ubuntu1404-docker` seems unavailable

### ISSUE THREAD

**Issue by kaylynb** [g0t4/consul-getting-started#1]
Looking at the atlas page it looks like it's gone:
https://atlas.hashicorp.com/boxcutter

Not sure why it's been delisted, but searching issues at boxcutter indicates that they may not be interested in building docker images anymore: https://github.com/boxcutter/ubuntu/issues/49

As a workaround, I just added the docker install steps to the vagrant provisioning step. Something like this:

```
sudo apt-get -y update
sudo apt-get -y install apt-transport-https ca-certificates
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list
sudo apt-get -y update
sudo apt-get -y install docker-engine
```

**Comment by g0t4** [comment]
:(
https://github.com/boxcutter/ubuntu/commit/249a96a65a41b1c7f9e366c905f310765cc28079

Thanks for sharing this, here's a link for others that might run into this,
I'll get something added to the videos to address this

Per https://docs.docker.com/v1.11/linux/step_one/ this might be the fastest
route, I'll test this and see if it works with the lab:

curl -fsSL https://get.docker.com/ | sh

**Comment by g0t4** [comment]
I re-packaged a copy of the vagrant boxes that I had locally and uploaded them to my own account, try the following slug:

wesmcclure/ubuntu1404-docker 

https://atlas.hashicorp.com/wesmcclure/boxes/ubuntu1404-docker

**Comment by g0t4** [comment]
@kaylynb will you test the new box and let me know if you have any trouble? It worked for me.

**Comment by kaylynb** [comment]
I won't be able to try it out for a few days (don't use virtualbox on my personal computer), but it should just work. Only issue may be that it isn't getting rebuilt with the latest updates like the boxcutter versions.

**Comment by g0t4** [comment]
Yeah I can't really update this one but it should be fine as it's just a
lab env that doesn't really need updates to work.

**Comment by rabin999** [comment]
> I re-packaged a copy of the vagrant boxes that I had locally and uploaded them to my own account, try the following slug:
> 
> wesmcclure/ubuntu1404-docker
> 
> https://atlas.hashicorp.com/wesmcclure/boxes/ubuntu1404-docker

Unable to found this package.
