### ISSUE TITLE
 Failed to create the host-only adapter

### ISSUE THREAD

**Issue by naliniranjan82** [g0t4/consul-getting-started#10]
Vagrant file detail:
Vagrant.configure("2") do |config|
  config.vm.box = "wesmcclure/ubuntu1404-docker"
  
  config.vm.define "consul-server" do |cs|
    cs.vm.hostname = "consul-server"
    cs.vm.network "private_network", ip: "172.20.20.31"
	end
end

F:\workspace\consul>vagrant up
Bringing machine 'consul-server' up with 'virtualbox' provider...
==> consul-server: Importing base box 'wesmcclure/ubuntu1404-docker'...
==> consul-server: Matching MAC address for NAT networking...
==> consul-server: Checking if box 'wesmcclure/ubuntu1404-docker' is up to date...
==> consul-server: Setting the name of the VM: consul_consul-server_1509732179552_56577
==> consul-server: Fixed port collision for 22 => 2222. Now on port 2200.
==> consul-server: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: E_INVALIDARG
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Assertion failed: [!aInterfaceName.isEmpty()] at 'F:\tinderbox\win-5.0\src\VBox\Main\src-server\HostNetworkInterfaceImpl.cpp' (74) in long __cdecl HostNetworkInterface::init(class com::Bstr,class com::Bstr,class com::Guid,enum __MIDL___MIDL_itf_VirtualBox_0000_0000_0036).
VBoxManage.exe: error: Please contact the product vendor!
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 71 of file VBoxManageHostonly.cpp

F:\workspace\consul>vagrant ssh consul-server
VM must be running to open SSH connection. Run `vagrant up`
to start the virtual machine

**Comment by g0t4** [comment]
Lookup the error from Virtual Box (VBoxManage), I've never encountered this.
