### ISSUE TITLE
Initial Configs Fail

### ISSUE THREAD

**Issue by farmerbean** [g0t4/consul-getting-started#2]
consul agent fails initially because common.json missing "retry_join" and also access denied because data_dir set to /opt/consul.

**Comment by g0t4** [comment]
You did a git clone and vagrant up and this happened?

**Comment by farmerbean** [comment]
Hiya Wes! Yes - I ended up using the config from the 'getting started with consul' and copying it into the deploying consul early config files ..

**Comment by g0t4** [comment]
Ok, things are working now?

 You will have to tweak with your atlas key in some of the branches of this
repo. Or take out Atlas joining

**Comment by farmerbean** [comment]
Yeah got it there - all part of the fun. Thanks Wes, really enjoying your courses!

**Comment by g0t4** [comment]
Yes indeed, and a good thing to work through too to get familiar with the
configuration options.

I'm happy to hear you're enjoying the course.
