### ISSUE TITLE
consul 0.7.2

### ISSUE THREAD

**Issue by jdkorigan** [g0t4/consul-getting-started#4]
Hello,
Your course is great and everything works fine, but I wanted to change to a more recent version of Consul and connection (for your exercise 2) doesn't work between the server one and local node.

Do you have any idea, what I would have to change to make it work?

Thank you

Best regards,

**Comment by g0t4** [comment]
Hrm, I just took 0.7.2 for a spin on the example in this repository and things seem ok. What error are you getting? Maybe that can help hunt down the issue.

**Comment by g0t4** [comment]
FYI https://github.com/g0t4/consul-getting-started/commit/022bac05ea0f3e05470eaa835839a669eb010d85 is the latest test commit

**Comment by g0t4** [comment]
You might also check vbox networking, see #5 for another example where vbox networking was likely the culprit for local (desktop) -> server connectivity. I'm going to close this for now, reopen if you still have issues.
