### ISSUE TITLE
i/o timeout with port 8301

### ISSUE THREAD

**Issue by neelamari** [g0t4/consul-getting-started#5]
Following through course. 
Got consul-server up and running 
`   consul agent -dev -advertise 172.20.20.31 `

Tried next step of running agent from desktop (mac) 
`   consul agent -config-file desky.json`

Get timeout errors and 
```
   2017/02/28 21:50:00 [INFO] serf: EventMemberJoin: neelamari 172.20.20.1
    2017/02/28 21:50:00 [WARN] manager: No servers available
    2017/02/28 21:50:00 [ERR] agent: failed to sync remote state: No known Consul servers
    2017/02/28 21:50:00 [INFO] agent: Joining cluster...
    2017/02/28 21:50:00 [INFO] agent: (LAN) joining: [172.20.20.31]
    2017/02/28 21:50:10 [INFO] agent: (LAN) joined: 0 Err: 1 error(s) occurred:

* Failed to join 172.20.20.31: dial tcp 172.20.20.31:8301: i/o timeout
    2017/02/28 21:50:10 [WARN] agent: Join failed: <nil>, retrying in 30s
    2017/02/28 21:50:24 [WARN] manager: No servers available
    2017/02/28 21:50:24 [ERR] agent: failed to sync remote state: No known Consul servers
```

Is there any needs to open ports in the server. The default image seems to have firewall disabled.  Appreciate help.

**Comment by g0t4** [comment]
Can you ping the server from your desktop? on 172.20.20.31?

**Comment by neelamari** [comment]
Hi Wes, couldn't ping. it times out

**Comment by neelamari** [comment]
Tried other samples from git and didn't work as well. Reinstalled vagrant and virtualbox and then everything worked. Thank you.

**Comment by g0t4** [comment]
Sometimes virtualbox networking builds up cruft and needs cleaned out to
fix things too. I believe at one point I found it had two of the same
networks set up with the same subnets and that was causing me grief :)

**Comment by ram-devsecops** [comment]
Hi @g0t4 , I'm getting similar error unable to join the consul-server. I'm able to ping the consul-server ip from my mac..Could you pls let me know how to fix this?

[consul-lab user$ consul agent -config-file consul.json 
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
           Version: 'v0.7.5'
           Node ID: '0badd3ca-3553-380f-8a09-3b02ba961b45'
         Node name: '-MAC'
        Datacenter: 'dc1'
            Server: false (bootstrap: false)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
      Cluster Addr: 172.20.20.1 (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>

==> Log data will now stream in as it occurs:

    2017/03/03 18:52:38 [INFO] serf: EventMemberJoin:MAC 172.20.20.1
    2017/03/03 18:52:38 [INFO] agent: Joining cluster...
    2017/03/03 18:52:38 [INFO] agent: (LAN) joining: [172.20.20.31]
    2017/03/03 18:52:38 [WARN] manager: No servers available
    2017/03/03 18:52:38 [ERR] agent: failed to sync remote state: No known Consul servers
    2017/03/03 18:52:48 [INFO] agent: (LAN) joined: 0 Err: 1 error(s) occurred:

* Failed to join 172.20.20.31: dial tcp 172.20.20.31:8301: i/o timeout
    2017/03/03 18:52:48 [WARN] agent: Join failed: <nil>, retrying in 30s
    2017/03/03 18:52:53 [WARN] manager: No servers available
    2017/03/03 18:52:53 [ERR] agent: failed to sync remote state: No known Consul servers
    2017/03/03 18:53:10 [WARN] manager: No servers available
    2017/03/03 18:53:10 [ERR] http: Request GET /v1/catalog/datacenters, error: No known Consul servers from=127.0.0.1:62811
    2017/03/03 18:53:12 [WARN] manager: No servers available
    2017/03/03 18:53:12 [ERR] http: Request GET /v1/catalog/datacenters, error: No known Consul servers from=127.0.0.1:62811
    2017/03/03 18:53:18 [INFO] agent: (LAN) joining: [172.20.20.31]
    2017/03/03 18:53:23 [WARN] manager: No servers available
    2017/03/03 18:53:23 [ERR] agent: failed to sync remote state: No known Consul servers
    2017/03/03 18:53:28 [INFO] agent: (LAN) joined: 0 Err: 1 error(s) occurred:

* Failed to join 172.20.20.31: dial tcp 172.20.20.31:8301: i/o timeout
    2017/03/03 18:53:28 [WARN] agent: Join failed: <nil>, retrying in 30s
    2017/03/03 18:53:41 [WARN] manager: No servers available
    2017/03/03 18:53:41 [ERR] agent: failed to sync remote state: No known Consul servers
    2017/03/03 18:53:58 [INFO] agent: (LAN) joining: [172.20.20.31]
    2017/03/03 18:54:05 [WARN] manager: No servers available
    2017/03/03 18:54:05 [ERR] agent: failed to sync remote state: No known Consul servers
    2017/03/03 18:54:08 [INFO] agent: (LAN) joined: 0 Err: 1 error(s) occurred:

* Failed to join 172.20.20.31: dial tcp 172.20.20.31:8301: i/o timeout
    2017/03/03 18:54:08 [WARN] agent: Join failed: <nil>, retrying in 30s](url)

**Comment by g0t4** [comment]
@rammaram06 did you check vbox networking for issues? see above discussion

**Comment by neelamari** [comment]
If you are using new version of consul (0.7.5), one thing I did which worked for me was to use -bind instead of -advertise 

--instead of 
    consul agent -dev -advertise 172.20.20.31 
-- use 
    consul agent -dev -bind 172.20.20.31 -node consul-server

Once I made this change, worked for me.

**Comment by ram-devsecops** [comment]
@neelamari Thank you, it worked after using bind.

**Comment by roberto-belardo** [comment]
Same thing here. After changin advertise with bind it worked without problems.
